version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install --upgrade pip
    - python -m pip install poetry
    - POETRY_VIRTUALENVS_CREATE=false poetry install --no-interaction --no-ansi
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py

python:
  install: []
